name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Create executable with PyInstaller
        run: |
          python -m PyInstaller --onedir --windowed --name florr_auto_afk_lite main.py

      - name: Copy necessary files to dist directory
        run: |
          mkdir -p dist\florr_auto_afk_lite\models
          xcopy models\* dist\florr_auto_afk_lite\models\ /E /I
          copy config.json dist\florr_auto_afk_lite\
          copy set_opaque.js dist\florr_auto_afk_lite\
          mkdir -p dist\florr_auto_afk_lite\logs

      - name: Compress files into zip
        run: |
          cd dist
          powershell Compress-Archive -Path florr_auto_afk_lite -DestinationPath ..\florr_auto_afk_lite_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: florr_auto_afk_lite_windows
          path: florr_auto_afk_lite_windows.zip
          retention-days: 90

      - name: Create and Publish Release (on push)
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1-${{ github.run_number }}
          name: Windows Build v1.0.1-${{ github.run_number }}
          body: |
            Automated Windows build
            Commit SHA: ${{ github.sha }}
            Run Number: ${{ github.run_number }}
          files: florr_auto_afk_lite_windows.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}